config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :comments
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get '/services', :to => 'home#service'
  get '/blog', :to => 'home#blog'
  get '/contact_us', :to => 'home#contact'
  get '/about', :to => 'home#about', as: 'about'
  get '/book_appoinment', :to => 'appointments#new'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to root_path, notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:name, :lastname, :number, :email, :city, :remark)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">
  <p>
    <strong>Name:</strong>
    <%= appointment.name %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= appointment.lastname %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= appointment.number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= appointment.email %>
  </p>

  <p>
    <strong>City:</strong>
    <%= appointment.city %>
  </p>

  <p>
    <strong>Remark:</strong>
    <%= appointment.remark %>
  </p>

</div>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field :lastname %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :remark, style: "display: block" %>
    <%= form.text_area :remark %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Show this appointment", @appointment %> |
  <%= link_to "Back to appointments", appointments_path %>
</div>

app/views/appointments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Appointments</h1>

<div id="appointments">
  <% @appointments.each do |appointment| %>
    <%= render appointment %>
    <p>
      <%= link_to "Show this appointment", appointment %>
    </p>
  <% end %>
</div>


<%= link_to "New appointment", new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Back to appointments", appointments_path %>
</div>

app/views/appointments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment %>

<div>
  <%= link_to "Edit this appointment", edit_appointment_path(@appointment) %> |
  <%= link_to "Back to appointments", appointments_path %>

  <%= button_to "Destroy this appointment", @appointment, method: :delete %>
</div>